### PR TITLE
Making Automated Dev a bit more visible on the map

### PR DESCRIPTION
**Pull request by SpiritBaker**

### CODE REVIEW

**Review by stackpoint — CHANGES_REQUESTED** [review]
This makes a lot of sense. However, the AI check is redundant because there is an AI check in the event trigger.

Also 360 vs 365?

**Comment by SpiritBaker** [comment]
Ups, I misclicked with request for review. Yea 365 sounds reasonable.

**Comment by SpiritBaker** [comment]
Now it should be fixed. I thought the event is also used by AI, my bad.

**Review by stackpoint — APPROVED** [review]
Looks good.

**Pull request merged**
